# Simple workflow for deploying static content to GitHub Pages
name: Run Selenium smoke test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "smoke-test"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install selenium pytest

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 'latest'

      - name: Run tests
        run: pytest
