# Simple workflow for deploying static content to GitHub Pages
name: Build and deploy Vue.js App to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single build and deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
        python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install selenium pytest

      - name: Set up ChromeDriver
        uses: browser-actions/setup-chromedriver@latest

      - name: Run tests
        run: pytest


